In [1]:
import pandas as pd
import numpy as np

In [2]:
df=pd.read_csv(r"C:\Users\Atharva\Downloads\archive (1)\Consumer_Complaints.csv\Consumer_Complaints.csv")

C:\Users\Atharva\AppData\Local\Temp\ipykernel_8364\2891527396.py:1: DtypeWarning: Columns (0: Consumer complaint narrative, 1: Consumer consent provided?) have mixed types. Specify dtype option on import or set low_memory=False.
  df=pd.read_csv(r"C:\Users\Atharva\Downloads\archive (1)\Consumer_Complaints.csv\Consumer_Complaints.csv")

In [3]:
df.head()

,Date received,Product,Sub-product,Issue,Sub-issue,Consumer complaint narrative,Company public response,Company,State,ZIP code,Tags,Consumer consent provided?,Submitted via,Date sent to company,Company response to consumer,Timely response?,Consumer disputed?,Complaint ID
0,07/29/2013,Consumer Loan,Vehicle loan,Managing the loan or lease,NaN,NaN,NaN,Wells Fargo & Company,VA,24540,NaN,NaN,Phone,07/30/2013,Closed with explanation,Yes,No,468882
1,07/29/2013,Bank account or service,Checking account,Using a debit or ATM card,NaN,NaN,NaN,Wells Fargo & Company,CA,95992,Older American,NaN,Web,07/31/2013,Closed with explanation,Yes,No,468889
2,07/29/2013,Bank account or service,Checking account,"Account opening, closing, or management",NaN,NaN,NaN,Santander Bank US,NY,10065,NaN,NaN,Fax,07/31/2013,Closed,Yes,No,468879
3,07/29/2013,Bank account or service,Checking account,Deposits and withdrawals,NaN,NaN,NaN,Wells Fargo & Company,GA,30084,NaN,NaN,Web,07/30/2013,Closed with explanation,Yes,No,468949
4,07/29/2013,Mortgage,Conventional fixed mortgage,"Loan servicing, payments, escrow account",NaN,NaN,NaN,Franklin Credit Management,CT,06106,NaN,NaN,Web,07/30/2013,Closed with explanation,Yes,No,475823

In [4]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 670598 entries, 0 to 670597
Data columns (total 18 columns):
 #   Column                        Non-Null Count   Dtype
---  ------                        --------------   -----
 0   Date received                 670598 non-null  str
 1   Product                       670598 non-null  str
 2   Sub-product                   472396 non-null  str
 3   Issue                         670598 non-null  str
 4   Sub-issue                     269868 non-null  str
 5   Consumer complaint narrative  114704 non-null  str
 6   Company public response       145197 non-null  str
 7   Company                       670598 non-null  str
 8   State                         665293 non-null  str
 9   ZIP code                      665274 non-null  str
 10  Tags                          94730 non-null   str
 11  Consumer consent provided?    208151 non-null  str
 12  Submitted via                 670598 non-null  str
 13  Date sent to company          670598 non-null  str
 14  Company response to consumer  670598 non-null  str
 15  Timely response?              670598 non-null  str
 16  Consumer disputed?            629179 non-null  str
 17  Complaint ID                  670598 non-null  int64
dtypes: int64(1), str(17)
memory usage: 318.6 MB

In [5]:
df.shape

(670598, 18)

In [6]:
df.isnull().sum()

Date received                        0
Product                              0
Sub-product                     198202
Issue                                0
Sub-issue                       400730
Consumer complaint narrative    555894
Company public response         525401
Company                              0
State                             5305
ZIP code                          5324
Tags                            575868
Consumer consent provided?      462447
Submitted via                        0
Date sent to company                 0
Company response to consumer         0
Timely response?                     0
Consumer disputed?               41419
Complaint ID                         0
dtype: int64

In [7]:
print(df['Consumer complaint narrative'].notna().sum())
print(df['Consumer complaint narrative'].isna().sum())
print(df.shape)

114704
555894
(670598, 18)

In [8]:
df.columns

Index(['Date received', 'Product', 'Sub-product', 'Issue', 'Sub-issue',
       'Consumer complaint narrative', 'Company public response', 'Company',
       'State', 'ZIP code', 'Tags', 'Consumer consent provided?',
       'Submitted via', 'Date sent to company', 'Company response to consumer',
       'Timely response?', 'Consumer disputed?', 'Complaint ID'],
      dtype='str')

In [9]:
df.head()

,Date received,Product,Sub-product,Issue,Sub-issue,Consumer complaint narrative,Company public response,Company,State,ZIP code,Tags,Consumer consent provided?,Submitted via,Date sent to company,Company response to consumer,Timely response?,Consumer disputed?,Complaint ID
0,07/29/2013,Consumer Loan,Vehicle loan,Managing the loan or lease,NaN,NaN,NaN,Wells Fargo & Company,VA,24540,NaN,NaN,Phone,07/30/2013,Closed with explanation,Yes,No,468882
1,07/29/2013,Bank account or service,Checking account,Using a debit or ATM card,NaN,NaN,NaN,Wells Fargo & Company,CA,95992,Older American,NaN,Web,07/31/2013,Closed with explanation,Yes,No,468889
2,07/29/2013,Bank account or service,Checking account,"Account opening, closing, or management",NaN,NaN,NaN,Santander Bank US,NY,10065,NaN,NaN,Fax,07/31/2013,Closed,Yes,No,468879
3,07/29/2013,Bank account or service,Checking account,Deposits and withdrawals,NaN,NaN,NaN,Wells Fargo & Company,GA,30084,NaN,NaN,Web,07/30/2013,Closed with explanation,Yes,No,468949
4,07/29/2013,Mortgage,Conventional fixed mortgage,"Loan servicing, payments, escrow account",NaN,NaN,NaN,Franklin Credit Management,CT,06106,NaN,NaN,Web,07/30/2013,Closed with explanation,Yes,No,475823

In [10]:
print(df['Product'].value_counts())

Product
Mortgage                   210324
Debt collection            124236
Credit reporting           119195
Credit card                 79007
Bank account or service     76084
Consumer Loan               26604
Student loan                21651
Payday loan                  4786
Money transfers              4720
Prepaid card                 3171
Other financial service       806
Virtual currency               14
Name: count, dtype: int64

In [11]:
print(df['Issue'].value_counts().head(15))

Issue
Loan modification,collection,foreclosure    106455
Incorrect information on credit report       86904
Loan servicing, payments, escrow account     70166
Cont'd attempts collect debt not owed        51590
Account opening, closing, or management      33347
Disclosure verification of debt              24578
Communication tactics                        21344
Deposits and withdrawals                     20325
Application, originator, mortgage broker     15518
Credit reporting company's investigation     13939
Billing disputes                             13170
Other                                        13081
Managing the loan or lease                   12718
Problems caused by my funds being low        10662
Dealing with my lender or servicer           10222
Name: count, dtype: int64

In [12]:
df.duplicated().sum()

np.int64(0)

In [13]:
df.columns

Index(['Date received', 'Product', 'Sub-product', 'Issue', 'Sub-issue',
       'Consumer complaint narrative', 'Company public response', 'Company',
       'State', 'ZIP code', 'Tags', 'Consumer consent provided?',
       'Submitted via', 'Date sent to company', 'Company response to consumer',
       'Timely response?', 'Consumer disputed?', 'Complaint ID'],
      dtype='str')

In [14]:
df=df[['Product','Issue','Company response to consumer','Consumer complaint narrative']]

In [15]:
df.head()

,Product,Issue,Company response to consumer,Consumer complaint narrative
0,Consumer Loan,Managing the loan or lease,Closed with explanation,NaN
1,Bank account or service,Using a debit or ATM card,Closed with explanation,NaN
2,Bank account or service,"Account opening, closing, or management",Closed,NaN
3,Bank account or service,Deposits and withdrawals,Closed with explanation,NaN
4,Mortgage,"Loan servicing, payments, escrow account",Closed with explanation,NaN

In [16]:
df.isnull().sum()

Product                              0
Issue                                0
Company response to consumer         0
Consumer complaint narrative    555894
dtype: int64

In [17]:
df.shape

(670598, 4)

In [18]:
df=df[df['Consumer complaint narrative'].notna()].copy()
print(df.shape)
print(df.isnull().sum())

(114704, 4)
Product                         0
Issue                           0
Company response to consumer    0
Consumer complaint narrative    0
dtype: int64

In [19]:
df.shape

(114704, 4)

In [20]:
print("Product")
print(df['Product'].value_counts())
print("Issue")
print(df['Issue'].value_counts().head(15))

Product
Product
Debt collection            28861
Mortgage                   24641
Credit reporting           22202
Credit card                13582
Bank account or service    10425
Consumer Loan               6394
Student loan                4948
Payday loan                 1245
Prepaid card                1144
Money transfers             1074
Other financial service      176
Virtual currency              12
Name: count, dtype: int64
Issue
Issue
Incorrect information on credit report      14762
Cont'd attempts collect debt not owed       12297
Loan servicing, payments, escrow account    10944
Loan modification,collection,foreclosure     8352
Disclosure verification of debt              5160
Account opening, closing, or management      4489
Communication tactics                        4370
Credit reporting company's investigation     3900
Dealing with my lender or servicer           3539
Managing the loan or lease                   2952
Application, originator, mortgage broker     2711
False statements or representation           2692
Deposits and withdrawals                     2384
Taking/threatening an illegal action         2209
Billing disputes                             2143
Name: count, dtype: int64

In [21]:
df.head()

,Product,Issue,Company response to consumer,Consumer complaint narrative
57729,Credit card,Other,Closed with explanation,Received Capital One charge card offer XXXX. A...
57787,Debt collection,Improper contact or sharing of info,Closed with explanation,I do n't know how they got my cell number. I t...
57838,Credit card,Rewards,Closed with explanation,I 'm a longtime member of Charter One Bank/RBS...
57848,Credit reporting,Incorrect information on credit report,Closed with non-monetary relief,"After looking at my credit report, I saw a col..."
57852,Debt collection,Improper contact or sharing of info,Closed with explanation,I received a call from a XXXX XXXX from XXXX @...

In [22]:
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.feature_selection import chi2
import pandas as pd

In [23]:
df['clean_text']=df['Consumer complaint narrative'].astype(str).str.lower().str.replace(r'[^a-z0-9\s]','',regex=True).str.strip()

In [24]:
cv=CountVectorizer()
X_counts = cv.fit_transform(df['clean_text'])
y_labels = df['Product']

In [25]:
chi_scores,p_value=chi2(X_counts,y_labels)

In [26]:
results=pd.DataFrame({
    'word':cv.get_feature_names_out(),
    'chi2_scores':chi_scores,
    'p_value':p_value
}).sort_values('chi2_scores',ascending=False)

print(results.head(20))

               word    chi2_scores  p_value
17881      coinbase  267614.666667      0.0
49395      mortgage  147363.493346      0.0
14995          card  130289.025521      0.0
45198          loan  116644.167617      0.0
45336         loans   90083.136229      0.0
75078           the   89133.731435      0.0
50540       navient   82201.968925      0.0
11143          bank   80127.937005      0.0
82457            we   78246.713280      0.0
22892          debt   72669.077892      0.0
72704       student   71581.830347      0.0
14984           car   63131.723559      0.0
48710  modification   62831.833737      0.0
76786            to   61545.821292      0.0
17882   coinbasecom   57346.000000      0.0
4363        account   55336.954092      0.0
54652           our   53899.955169      0.0
81066       vehicle   52472.215512      0.0
29008       equifax   50826.571538      0.0
37509          home   50358.486082      0.0

In [27]:
significant=(results['p_value'] < 0.05).sum()
total=len(results)
print(f"Significant words :{significant}/{total} ({significant/total*100:.1f}%)")

Significant words :20125/87268 (23.1%)

In [28]:
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import classification_report

In [29]:
def simplify_category(cat):
    if cat in ['Other financial service','Virtual currency']:
        return 'Other'
    return cat

In [31]:
print(df['Product_final'].value_counts())

Product_final
Debt collection            28861
Mortgage                   24641
Credit reporting           22202
Credit card                13582
Bank account or service    10425
Consumer Loan               6394
Student loan                4948
Payday loan                 1245
Prepaid card                1144
Money transfers             1074
Other                        188
Name: count, dtype: int64

In [32]:
df.head()

,Product,Issue,Company response to consumer,Consumer complaint narrative,clean_text,Product_final
57729,Credit card,Other,Closed with explanation,Received Capital One charge card offer XXXX. A...,received capital one charge card offer xxxx ap...,Credit card
57787,Debt collection,Improper contact or sharing of info,Closed with explanation,I do n't know how they got my cell number. I t...,i do nt know how they got my cell number i tol...,Debt collection
57838,Credit card,Rewards,Closed with explanation,I 'm a longtime member of Charter One Bank/RBS...,i m a longtime member of charter one bankrbs c...,Credit card
57848,Credit reporting,Incorrect information on credit report,Closed with non-monetary relief,"After looking at my credit report, I saw a col...",after looking at my credit report i saw a coll...,Credit reporting
57852,Debt collection,Improper contact or sharing of info,Closed with explanation,I received a call from a XXXX XXXX from XXXX @...,i received a call from a xxxx xxxx from xxxx ...,Debt collection

In [33]:
X=df['clean_text']
y=df['Product_final']

X_train,X_test,y_train,y_test=train_test_split(X,y,random_state=42,test_size=0.2,stratify=y)

In [34]:
X_train.shape[0]

91763

In [35]:
X_test.shape[0]

22941

In [36]:
df['Product_final'].value_counts()

Product_final
Debt collection            28861
Mortgage                   24641
Credit reporting           22202
Credit card                13582
Bank account or service    10425
Consumer Loan               6394
Student loan                4948
Payday loan                 1245
Prepaid card                1144
Money transfers             1074
Other                        188
Name: count, dtype: int64

In [37]:
def keyword_baseline(text):
    text=text.lower()
    if any(w in text for w in ['mortage','escrow','forclose']):
        return 'Mortgage'
    elif any(w in text for w in ['credit card','card']):
        return 'Credit card'
    elif any(w in text for w in ['debt collector','debt','owed']):
        return 'Debt collection'
    elif any(w in text for w in ['credit report','equifax','experian','transunion']):
        return 'Credit reporting'
    elif any(w in text for w in ['bank report','checking','atm','debit']):
        return 'Bank account or service'
    elif any(w in text for w in ['student loan','navient','sallie mae']):
        return 'Student loan'
    elif any(w in text for w in ['payday']):
        return 'Payday loan'
    elif any (w in text for w in ['prepaid']):
        return 'Prepaid card'
    elif any(w in text for w in ['wire transfer','money transfer','remittance']):
        return 'Money transfers'
    elif any(w in text for w in ['auto loan','car loan','vehicle loan']):
        return 'Consumer Loan'
    else:
        return 'Other'

In [38]:
baseline_preds=X_test.apply(keyword_baseline)
print(classification_report(y_test,baseline_preds))

                         precision    recall  f1-score   support

Bank account or service       0.60      0.22      0.32      2085
          Consumer Loan       0.78      0.09      0.16      1279
            Credit card       0.48      0.77      0.59      2716
       Credit reporting       0.70      0.53      0.60      4440
        Debt collection       0.56      0.57      0.57      5772
        Money transfers       0.67      0.13      0.22       215
               Mortgage       0.95      0.17      0.29      4928
                  Other       0.00      0.42      0.00        38
            Payday loan       0.53      0.16      0.25       249
           Prepaid card       0.08      0.00      0.01       229
           Student loan       0.85      0.35      0.50       990

               accuracy                           0.42     22941
              macro avg       0.57      0.31      0.32     22941
           weighted avg       0.69      0.42      0.45     22941

In [39]:
#3 Now we will use our method b which is the trained model
tfidf=TfidfVectorizer(stop_words='english',ngram_range=(1,2),max_features=5000)
tfidf_train=tfidf.fit_transform(X_train)
tfidf_test=tfidf.transform(X_test)

In [40]:
lr=LogisticRegression()
lr.fit(tfidf_train,y_train)
lr_preds=lr.predict(tfidf_test)

print(classification_report(y_test,lr_preds))

                         precision    recall  f1-score   support

Bank account or service       0.84      0.81      0.82      2085
          Consumer Loan       0.77      0.63      0.69      1279
            Credit card       0.81      0.82      0.82      2716
       Credit reporting       0.87      0.88      0.87      4440
        Debt collection       0.82      0.88      0.85      5772
        Money transfers       0.75      0.52      0.62       215
               Mortgage       0.93      0.95      0.94      4928
                  Other       1.00      0.03      0.05        38
            Payday loan       0.66      0.36      0.47       249
           Prepaid card       0.84      0.63      0.72       229
           Student loan       0.90      0.82      0.86       990

               accuracy                           0.85     22941
              macro avg       0.83      0.67      0.70     22941
           weighted avg       0.85      0.85      0.85     22941

c:\Users\Atharva\cs corner\GenerativeAi\venv\Lib\site-packages\sklearn\linear_model\_logistic.py:599: ConvergenceWarning: lbfgs failed to converge after 100 iteration(s) (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT

Increase the number of iterations to improve the convergence (max_iter=100).
You might also want to scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

In [41]:
from sklearn.svm import LinearSVC
from sklearn.ensemble import RandomForestClassifier
svc=LinearSVC(class_weight='balanced',max_iter=2000)
svc.fit(tfidf_train,y_train)
svc_preds=svc.predict(tfidf_test)
print(classification_report(y_test,svc_preds))

                         precision    recall  f1-score   support

Bank account or service       0.82      0.79      0.80      2085
          Consumer Loan       0.68      0.67      0.67      1279
            Credit card       0.80      0.81      0.80      2716
       Credit reporting       0.88      0.87      0.88      4440
        Debt collection       0.86      0.83      0.85      5772
        Money transfers       0.58      0.67      0.63       215
               Mortgage       0.93      0.94      0.94      4928
                  Other       0.30      0.24      0.26        38
            Payday loan       0.43      0.60      0.50       249
           Prepaid card       0.65      0.76      0.70       229
           Student loan       0.83      0.87      0.85       990

               accuracy                           0.84     22941
              macro avg       0.70      0.73      0.72     22941
           weighted avg       0.85      0.84      0.84     22941

In [42]:
import os 
from groq import Groq
import pandas as pd
import time
from sklearn.metrics import classification_report
client=Groq(api_key=os.environ.get('GROQ_API_KEY'))

#3 small sample because llm calls take time/tokens
sample_df=pd.DataFrame({'text':X_test,'true_labels':y_test}).sample(100,random_state=42)

categories=df['Product_final'].unique().tolist()

def llm_classifier(text):
    prompt=f"""Classifiy the consumer complaint into exactly one of these categories {categories}
    Complaint:"{text[:500]}"
    Reply With only the catgeory name,nothing else"""
    response=client.chat.completions.create(
        model='openai/gpt-oss-20b',
        messages=[{'role':'user','content':prompt}],
        temperature=0      
    )
    time.sleep(2)
    return response.choices[0].message.content.strip()

In [ ]:
sample_df['llm_pred']=sample_df['text'].apply(llm_classifier)
print(classification_report(sample_df['true_labels'],sample_df['llm_pred'],zero_division=0))

In [ ]:
import nltk
nltk.download('vader_lexicon')

In [45]:
from nltk.sentiment.vader import SentimentIntensityAnalyzer
sia=SentimentIntensityAnalyzer()

In [46]:
df['sentiment_score']=df['clean_text'].apply(lambda x:sia.polarity_scores(x)['compound'])

In [47]:
def sentiment_label(score):
    if score <= -0.5:
        return 'Angry'
    elif score <= 0:
        return 'Frustrated'
    else:
        return 'Calm/Neutral'

In [48]:
df['sentiment']=df['sentiment_score'].apply(sentiment_label)
print(df['sentiment'].value_counts())

sentiment
Calm/Neutral    52074
Angry           40557
Frustrated      22073
Name: count, dtype: int64

In [49]:
from langchain_community.embeddings import HuggingFaceInferenceAPIEmbeddings
from langchain_community.vectorstores import FAISS

C:\Users\Atharva\AppData\Local\Temp\ipykernel_8364\3626043164.py:1: DeprecationWarning: `langchain-community` is being sunset and is no longer actively maintained. See https://github.com/langchain-ai/langchain-community/issues/674 for details and migration guidance toward standalone integration packages.
  from langchain_community.embeddings import HuggingFaceInferenceAPIEmbeddings

In [50]:
from policies import POLICIES

In [51]:
from langchain_community.docstore.document import Document
docs=[
    Document(page_content=p['content'],metadata={'id':p['id'],'title':p['title']})
    for p in POLICIES
]

In [52]:
from langchain_huggingface import HuggingFaceEndpointEmbeddings

c:\Users\Atharva\cs corner\GenerativeAi\venv\Lib\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

In [54]:
import os
embeddings=HuggingFaceInferenceAPIEmbeddings(
    model_name="sentence-transformers/all-MiniLM-L6-v2",
    api_key=os.getenv('HUGGINGFACEHUB_API_TOKEN')
)

C:\Users\Atharva\AppData\Local\Temp\ipykernel_8364\4052158812.py:2: LangChainDeprecationWarning: The class `HuggingFaceInferenceAPIEmbeddings` was deprecated in LangChain 0.2.2 and will be removed in 1.0. An updated version of the class exists in the `langchain-huggingface package and should be used instead. To use it run `pip install -U `langchain-huggingface` and import as `from `langchain_huggingface import HuggingFaceEndpointEmbeddings``.
  embeddings=HuggingFaceInferenceAPIEmbeddings(

In [56]:
from langchain_community.embeddings import HuggingFaceEmbeddings
embeddings=HuggingFaceEmbeddings(model_name='sentence-transformers/all-MiniLM-L6-v2')

C:\Users\Atharva\AppData\Local\Temp\ipykernel_8364\177069308.py:2: LangChainDeprecationWarning: The class `HuggingFaceEmbeddings` was deprecated in LangChain 0.2.2 and will be removed in 1.0. An updated version of the class exists in the `langchain-huggingface package and should be used instead. To use it run `pip install -U `langchain-huggingface` and import as `from `langchain_huggingface import HuggingFaceEmbeddings``.
  embeddings=HuggingFaceEmbeddings(model_name='sentence-transformers/all-MiniLM-L6-v2')
Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.
Loading weights: 100%|██████████| 103/103 [00:00<00:00, 5238.49it/s]

In [57]:
vector_store=FAISS.from_documents(docs,embeddings)

In [58]:
test_queries=[
    'my mortage payement was applied to the wrong account and now they are saying i own late fees',
    'debt collector keeps calling my workplace even after i asked them to stop',
    'somenone opened a credit card in my name that i never applied for '
]

for query in test_queries:
    result=vector_store.similarity_search_with_score(query,k=2)
    print(f"Query:{query}")
    for doc,score in result:
        print(f"Scores {score:.3f} | {doc.metadata['title']}: {doc.page_content[:100]}...")

Query:my mortage payement was applied to the wrong account and now they are saying i own late fees
Scores 0.814 | Misapplied Mortgage Payments: Payments applied to the wrong account or misallocated between principal and interest must be correct...
Scores 1.106 | Overdraft Fee Disputes: Disputed overdraft fees are reviewed within 5 business days against the account's opt-in overdraft a...
Query:debt collector keeps calling my workplace even after i asked them to stop
Scores 0.996 | Third-Party Contact Complaints: Complaints about collectors contacting family, friends, or employers must be escalated immediately, ...
Scores 1.027 | Debt Verification Requests: Consumers requesting debt verification must receive validation documentation within 30 days; collect...
Query:somenone opened a credit card in my name that i never applied for
Scores 1.182 | Card Application Denial: Credit card application denials must include an adverse action notice with specific reasons, sent wi...
Scores 1.210 | Registration/Activation Failures: Complaints about failed card registration or activation preventing access to funds are resolved with...

In [59]:
vector_store.save_local("policy_index")
print("Saved")

Saved

In [60]:
import pickle
pickle.dump(tfidf,open('tfidf_vectorizer.pkl','wb'))
pickle.dump(lr,open('lr_model.pkl','wb'))